spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:travel_guide
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database: h2
    generate-ddl: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.format-sql: true
    show-sql: true

  flyway:
    baseline-on-migrate: true
    enabled: true
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    schemas:
      - PUBLIC

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://${DISCOVERY_HOST:localhost}:${DISCOVERY_PORT:8761}/eureka/}
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

management:
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
